# Generated by Django 4.2.7 on 2025-11-09 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('categoria', models.CharField(choices=[('SEG', 'Segurança do Trabalho'), ('SAU', 'Saúde do Trabalhador')], max_length=3)),
                ('data', models.DateField()),
                ('observacao', models.TextField(blank=True, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Relatório',
                'verbose_name_plural': 'Relatórios',
                'ordering': ('-data', '-criado_em'),
            },
        ),
        migrations.CreateModel(
            name='RelatorioAtividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('contador', models.PositiveIntegerField(default=0)),
                ('ordem', models.PositiveIntegerField(default=0)),
                ('relatorio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='relatorios.relatorio')),
            ],
            options={
                'verbose_name': 'Atividade do Relatório',
                'verbose_name_plural': 'Atividades do Relatório',
                'ordering': ('ordem', 'id'),
            },
        ),
    ]
