# Generated by Django 4.2.7 on 2025-10-07 23:46

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AmbienteDeTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Ambiente')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Ambiente')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.empresa', verbose_name='Empresa')),
            ],
            options={
                'verbose_name': 'Ambiente de Trabalho',
                'verbose_name_plural': 'Ambientes de Trabalho',
            },
        ),
        migrations.CreateModel(
            name='Exame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_esocial', models.CharField(help_text='Código correspondente à Tabela 27 do eSocial.', max_length=10, unique=True, verbose_name='Código eSocial')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Procedimento Diagnóstico')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Exame',
                'verbose_name_plural': 'Exames (Tabela 27)',
            },
        ),
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_esocial', models.CharField(help_text='Código correspondente à Tabela 24 do eSocial.', max_length=10, unique=True, verbose_name='Código eSocial')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Risco')),
                ('tipo', models.CharField(choices=[('FIS', 'Físico'), ('QUI', 'Químico'), ('BIO', 'Biológico'), ('ERG', 'Ergonômico'), ('ACI', 'Acidentes/Mecânico')], max_length=3, verbose_name='Tipo do Risco')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição do Risco/Fonte Geradora')),
            ],
            options={
                'verbose_name': 'Risco',
                'verbose_name_plural': 'Riscos (Tabela 24)',
            },
        ),
        migrations.CreateModel(
            name='ExposicaoRisco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensidade', models.CharField(blank=True, max_length=100, null=True, verbose_name='Intensidade/Concentração')),
                ('tecnica_utilizada', models.CharField(blank=True, max_length=200, null=True, verbose_name='Técnica Utilizada para Medição')),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.ambientedetrabalho', verbose_name='Ambiente de Trabalho')),
                ('cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.cargo', verbose_name='Cargo')),
                ('risco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.risco', verbose_name='Risco')),
            ],
            options={
                'verbose_name': 'Exposição de Risco',
                'verbose_name_plural': 'Exposições de Riscos',
            },
        ),
        migrations.CreateModel(
            name='Aso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('ADM', 'Admissional'), ('PER', 'Periódico'), ('RET', 'Retorno ao Trabalho'), ('MUD', 'Mudança de Risco Ocupacional'), ('DEM', 'Demissional')], max_length=3, verbose_name='Tipo de ASO')),
                ('resultado', models.CharField(choices=[('AP', 'Apto'), ('IN', 'Inapto')], max_length=2, verbose_name='Resultado')),
                ('data_exame', models.DateField(default=django.utils.timezone.now, verbose_name='Data do Exame')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='Data de Vencimento')),
                ('medico_responsavel_nome', models.CharField(max_length=200, verbose_name='Nome do Médico Responsável')),
                ('medico_responsavel_crm', models.CharField(max_length=20, verbose_name='CRM do Médico Responsável')),
                ('exames_realizados', models.ManyToManyField(to='core.exame', verbose_name='Exames Realizados')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.funcionario', verbose_name='Funcionário')),
            ],
            options={
                'verbose_name': 'ASO - Atestado de Saúde Ocupacional',
                'verbose_name_plural': 'ASOs - Atestados de Saúde Ocupacional',
                'ordering': ['-data_exame'],
            },
        ),
        migrations.AddConstraint(
            model_name='exposicaorisco',
            constraint=models.UniqueConstraint(fields=('cargo', 'ambiente', 'risco'), name='unique_exposicao_risco'),
        ),
        migrations.AlterUniqueTogether(
            name='ambientedetrabalho',
            unique_together={('empresa', 'nome')},
        ),
    ]
