# Generated by Django 4.2.7 on 2025-10-15 00:17

from django.db import migrations

# --- DICIONÁRIO DE DADOS ESSENCIAIS DE SST (TABELAS ESOCIAL) ---
DADOS_SST = {
    "tabela_24_riscos": [
        # Código, Nome, Tipo (conforme TipoRisco em models.py)
        # Físicos
        ("01.01.001", "Ruído", "FIS"),
        ("01.02.001", "Calor", "FIS"),
        ("01.05.001", "Radiações Ionizantes", "FIS"),
        # Químicos
        ("02.01.445", "Formaldeído (formol)", "QUI"),
        ("02.01.275", "Gases anestésicos", "QUI"),
        ("02.01.026", "Arsênio e seus compostos", "QUI"),
        # Biológicos
        ("03.01.001", "Microorganismos e parasitas infecto-contagiosos vivos e suas toxinas", "BIO"),
        # Ergonômicos e de Acidentes (Exemplos, pois não geram aposentadoria especial)
        ("09.01.001", "Ausência de fator de risco ou de atividades previstas no Anexo IV do Decreto 3.048/1999", "ACI"), # Usado quando não há risco
    ],
    "tabela_27_exames": [
        # Código, Nome
        ("0231", "AVALIAÇÃO CLÍNICA OCUPACIONAL"),
        ("0201", "HEMOGRAMA COMPLETO"),
        ("1324", "AUDIOMETRIA"),
        ("1601", "ESPIROMETRIA"),
        ("1801", "RADIOGRAFIA DE TÓRAX (P.A.)"),
        ("1269", "ELETROCARDIOGRAMA"),
        ("1271", "ELETROENCEFALOGRAMA"),
    ]
}

def popular_tabelas_base(apps, schema_editor):
    """
    Função que cadastra os Riscos e Exames das tabelas do eSocial.
    """
    Risco = apps.get_model('core', 'Risco')
    Exame = apps.get_model('core', 'Exame')

    # Cadastra Riscos da Tabela 24
    for codigo, nome, tipo in DADOS_SST["tabela_24_riscos"]:
        Risco.objects.get_or_create(
            codigo_esocial=codigo,
            defaults={'nome': nome, 'tipo': tipo}
        )

    # Cadastra Exames da Tabela 27
    for codigo, nome in DADOS_SST["tabela_27_exames"]:
        Exame.objects.get_or_create(
            codigo_esocial=codigo,
            defaults={'nome': nome}
        )

def limpar_tabelas_base(apps, schema_editor):
    """
    Função reversa que limpa os dados inseridos.
    """
    Risco = apps.get_model('core', 'Risco')
    Exame = apps.get_model('core', 'Exame')
    Risco.objects.all().delete()
    Exame.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ambientedetrabalho_exame_risco_exposicaorisco_aso_and_more'),
    ]

    operations = [
        migrations.RunPython(popular_tabelas_base, reverse_code=limpar_tabelas_base),
    ]