# Generated by Django 4.2.7 on 2025-11-09 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('descricao', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Inventário de Perigos e Riscos',
                'verbose_name_plural': 'Inventários de Perigos e Riscos',
            },
        ),
        migrations.CreateModel(
            name='Risco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_esocial', models.CharField(max_length=10, unique=True, verbose_name='Código eSocial')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome do Risco')),
                ('tipo', models.CharField(choices=[('FIS', 'Físico'), ('QUI', 'Químico'), ('BIO', 'Biológico'), ('ERG', 'Ergonômico'), ('ACI', 'Acidente/Mecânico')], max_length=3, verbose_name='Tipo do Risco')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
            ],
            options={
                'verbose_name': 'Risco',
                'verbose_name_plural': 'Riscos (Tab. 24)',
            },
        ),
        migrations.CreateModel(
            name='MedidaControle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('ELI', 'Eliminação'), ('SUB', 'Substituição'), ('EPC', 'Proteção Coletiva'), ('ADM', 'Administrativa'), ('EPI', 'Proteção Individual')], max_length=3)),
                ('risco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medidas', to='pgr.risco')),
            ],
            options={
                'verbose_name': 'Medida de Controle',
                'verbose_name_plural': 'Medidas de Controle',
            },
        ),
        migrations.CreateModel(
            name='Exposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('probabilidade', models.PositiveSmallIntegerField(default=1)),
                ('severidade', models.PositiveSmallIntegerField(default=1)),
                ('intensidade', models.CharField(blank=True, max_length=100, null=True)),
                ('tecnica_utilizada', models.CharField(blank=True, max_length=200, null=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exposicoes', to='org.ambientetrabalho')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exposicoes', to='org.funcao')),
                ('risco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='exposicoes', to='pgr.risco')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exposicoes', to='hr.vinculo')),
            ],
            options={
                'verbose_name': 'Exposição a Risco',
                'verbose_name_plural': 'Exposições a Riscos',
            },
        ),
        migrations.AddConstraint(
            model_name='exposicao',
            constraint=models.UniqueConstraint(fields=('vinculo', 'ambiente', 'risco'), name='unique_exposicao_vinculo'),
        ),
    ]
