# Generated by Django 4.2.7 on 2025-11-09 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
        ('pgr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapaExposicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intensidade', models.CharField(blank=True, max_length=100, null=True)),
                ('tecnica_utilizada', models.CharField(blank=True, max_length=200, null=True)),
                ('ambiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapas_exposicao', to='org.ambientetrabalho')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mapas_exposicao', to='org.funcao')),
                ('risco', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mapas_exposicao', to='pgr.risco')),
            ],
            options={
                'verbose_name': 'Mapa de Exposição (Função/Ambiente)',
                'verbose_name_plural': 'Mapas de Exposição (Função/Ambiente)',
            },
        ),
        migrations.AddConstraint(
            model_name='mapaexposicao',
            constraint=models.UniqueConstraint(fields=('funcao', 'ambiente', 'risco'), name='unique_mapa_exposicao'),
        ),
    ]
