# Generated by Django 4.2.7 on 2025-11-09 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incidente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateTimeField()),
                ('tipo', models.CharField(max_length=100)),
                ('gravidade', models.CharField(choices=[('LEV', 'Leve'), ('MOD', 'Moderada'), ('GRA', 'Grave')], max_length=3)),
                ('local', models.CharField(max_length=150)),
                ('descricao', models.TextField()),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incidentes', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Incidente/Acidente',
                'verbose_name_plural': 'Incidentes/Acidentes',
                'ordering': ('-data',),
            },
        ),
        migrations.CreateModel(
            name='Investigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cinco_porques', models.TextField(blank=True, null=True)),
                ('arvore_causas', models.TextField(blank=True, null=True)),
                ('incidente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='investigacao', to='incidentes.incidente')),
            ],
            options={
                'verbose_name': 'Investigação',
                'verbose_name_plural': 'Investigações',
            },
        ),
        migrations.CreateModel(
            name='Acao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=150)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='aberta', max_length=50)),
                ('incidente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='acoes', to='incidentes.incidente')),
            ],
            options={
                'verbose_name': 'Ação do Incidente',
                'verbose_name_plural': 'Ações do Incidente',
            },
        ),
    ]
