# Generated by Django 4.2.7 on 2025-11-09 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checklist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='org.setor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='checklists', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Checklist',
                'verbose_name_plural': 'Checklists',
                'unique_together': {('setor', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='ChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=255)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='inspecoes.checklist')),
            ],
            options={
                'verbose_name': 'Item do Checklist',
                'verbose_name_plural': 'Itens do Checklist',
            },
        ),
        migrations.CreateModel(
            name='Inspecao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('realizada_em', models.DateTimeField(auto_now_add=True)),
                ('responsavel', models.CharField(max_length=150)),
                ('status', models.CharField(choices=[('ABE', 'Aberta'), ('AND', 'Em andamento'), ('CON', 'Concluída')], default='ABE', max_length=3)),
                ('checklist', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inspecoes', to='inspecoes.checklist')),
            ],
            options={
                'verbose_name': 'Inspeção',
                'verbose_name_plural': 'Inspeções',
            },
        ),
        migrations.CreateModel(
            name='NaoConformidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=255)),
                ('responsavel', models.CharField(max_length=150)),
                ('prazo', models.DateField(blank=True, null=True)),
                ('status', models.CharField(default='aberta', max_length=50)),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nao_conformidades', to='inspecoes.inspecao')),
            ],
            options={
                'verbose_name': 'Não Conformidade',
                'verbose_name_plural': 'Não Conformidades',
            },
        ),
        migrations.CreateModel(
            name='InspecaoResposta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conforme', models.BooleanField(null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('foto', models.FileField(blank=True, null=True, upload_to='inspecoes/fotos/')),
                ('inspecao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='inspecoes.inspecao')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inspecoes.checklistitem')),
            ],
            options={
                'verbose_name': 'Resposta da Inspeção',
                'verbose_name_plural': 'Respostas de Inspeção',
            },
        ),
    ]
