# Generated by Django 4.2.7 on 2025-11-09 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Colaborador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_completo', models.CharField(max_length=200)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('pis', models.CharField(blank=True, max_length=20, null=True)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colaboradores', to='org.empresa')),
            ],
            options={
                'verbose_name': 'Colaborador',
                'verbose_name_plural': 'Colaboradores',
            },
        ),
        migrations.CreateModel(
            name='Vinculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_admissao', models.DateField()),
                ('data_demissao', models.DateField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('colaborador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vinculos', to='hr.colaborador')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='org.funcao')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='org.setor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vinculos', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Vínculo',
                'verbose_name_plural': 'Vínculos',
                'ordering': ('-ativo', '-data_admissao'),
            },
        ),
        migrations.AddConstraint(
            model_name='vinculo',
            constraint=models.UniqueConstraint(fields=('colaborador', 'funcao', 'unidade', 'setor', 'data_admissao'), name='unique_vinculo_inicio'),
        ),
    ]
