# Generated by Django 4.2.7 on 2025-11-09 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=200, verbose_name='Razão Social')),
                ('nome_fantasia', models.CharField(blank=True, max_length=200, null=True, verbose_name='Nome Fantasia')),
                ('cnpj', models.CharField(max_length=18, unique=True, verbose_name='CNPJ')),
                ('telefone', models.CharField(blank=True, max_length=30, null=True, verbose_name='Telefone')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
        ),
        migrations.CreateModel(
            name='Unidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Unidade')),
                ('cnpj', models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ')),
                ('endereco', models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidades', to='org.empresa')),
            ],
            options={
                'verbose_name': 'Unidade',
                'verbose_name_plural': 'Unidades',
                'unique_together': {('empresa', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Setor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Setor')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='setores', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Setor',
                'verbose_name_plural': 'Setores',
                'unique_together': {('unidade', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='Funcao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome da Função')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição das Atividades')),
                ('setor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcoes', to='org.setor')),
            ],
            options={
                'verbose_name': 'Função',
                'verbose_name_plural': 'Funções',
                'unique_together': {('setor', 'nome')},
            },
        ),
        migrations.CreateModel(
            name='AmbienteTrabalho',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do Ambiente')),
                ('descricao', models.TextField(blank=True, null=True, verbose_name='Descrição')),
                ('unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ambientes', to='org.unidade')),
            ],
            options={
                'verbose_name': 'Ambiente de Trabalho',
                'verbose_name_plural': 'Ambientes de Trabalho',
                'unique_together': {('unidade', 'nome')},
            },
        ),
    ]
