# Generated by Django 4.2.7 on 2025-11-09 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=150)),
                ('mensagem', models.TextField()),
                ('canal', models.CharField(choices=[('EMAIL', 'Email'), ('PAINEL', 'Painel')], default='PAINEL', max_length=10)),
                ('destino', models.CharField(help_text='Email ou identificador do destinatário', max_length=150)),
                ('disparada_em', models.DateTimeField(auto_now_add=True)),
                ('lida', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'Notificação',
                'verbose_name_plural': 'Notificações',
            },
        ),
    ]
