# Generated by Django 4.2.7 on 2025-11-09 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pgr', '0001_initial'),
        ('org', '0001_initial'),
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('numero_ca', models.CharField(max_length=30, unique=True, verbose_name='Número CA')),
                ('validade_ca', models.DateField(blank=True, null=True, verbose_name='Validade do CA')),
                ('fabricante', models.CharField(blank=True, max_length=150, null=True)),
            ],
            options={
                'verbose_name': 'EPI',
                'verbose_name_plural': 'EPIs',
            },
        ),
        migrations.CreateModel(
            name='EPIRequisito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requisitos', to='epis.epi')),
                ('funcao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_requisitos', to='org.funcao')),
                ('risco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='epis_requisitos', to='pgr.risco')),
            ],
            options={
                'verbose_name': 'Requisito de EPI',
                'verbose_name_plural': 'Requisitos de EPI',
            },
        ),
        migrations.CreateModel(
            name='EntregaEPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('entregue_em', models.DateField(auto_now_add=True)),
                ('aceite_digital', models.BooleanField(default=False)),
                ('aceite_em', models.DateTimeField(blank=True, null=True)),
                ('observacao', models.CharField(blank=True, max_length=255, null=True)),
                ('epi', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entregas', to='epis.epi')),
                ('vinculo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas_epi', to='hr.vinculo')),
            ],
            options={
                'verbose_name': 'Entrega de EPI',
                'verbose_name_plural': 'Entregas de EPI',
            },
        ),
        migrations.AddConstraint(
            model_name='epirequisito',
            constraint=models.UniqueConstraint(fields=('funcao', 'risco', 'epi'), name='unique_epi_requisito'),
        ),
    ]
